// This file was generated by running the command typeorm init --database postgres

// In typeORM entities are like models 

import { IsEmail, Length } from "class-validator";
import {Entity, PrimaryGeneratedColumn, Column, BaseEntity, Index, CreateDateColumn, UpdateDateColumn} from "typeorm";

@Entity('users')
export class User extends BaseEntity {

    // in a partial , some of the fields are allowed to be nullable
    constructor(user: Partial<User>){
        super()
        Object.assign(this,user)
    }
    @PrimaryGeneratedColumn()
    id: number;
    
    // adds an index on these fields which improves performance when querying the database
    @Index()
    @IsEmail()
    @Column({unique:true})
    email : string

    @Index()
    @Length(3, 20, {message : "Username must be atleast 3 characters long"})
    @Column({unique:true})
    username : string

    @Column()
    @Length(6)
    password : string

    // a build in typeorm property decorator that allows us to create a created at column
    @CreateDateColumn()
    createdAt : Date

    // a build in typeorm property decorator that allows us to create an updated at column
    @UpdateDateColumn()
    updatedAt : Date
}
